// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: meadplugin.proto

package meadplugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuleStatus int32

const (
	RuleStatus_RULE_STATUS_UNSPECIFIED RuleStatus = 0
	RuleStatus_RULE_STATUS_SUCCESS     RuleStatus = 1
	RuleStatus_RULE_STATUS_FAILURE     RuleStatus = 2
	RuleStatus_RULE_STATUS_RETRY       RuleStatus = 3
	RuleStatus_RULE_STATUS_SKIP        RuleStatus = 4
)

// Enum value maps for RuleStatus.
var (
	RuleStatus_name = map[int32]string{
		0: "RULE_STATUS_UNSPECIFIED",
		1: "RULE_STATUS_SUCCESS",
		2: "RULE_STATUS_FAILURE",
		3: "RULE_STATUS_RETRY",
		4: "RULE_STATUS_SKIP",
	}
	RuleStatus_value = map[string]int32{
		"RULE_STATUS_UNSPECIFIED": 0,
		"RULE_STATUS_SUCCESS":     1,
		"RULE_STATUS_FAILURE":     2,
		"RULE_STATUS_RETRY":       3,
		"RULE_STATUS_SKIP":        4,
	}
)

func (x RuleStatus) Enum() *RuleStatus {
	p := new(RuleStatus)
	*p = x
	return p
}

func (x RuleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_meadplugin_proto_enumTypes[0].Descriptor()
}

func (RuleStatus) Type() protoreflect.EnumType {
	return &file_meadplugin_proto_enumTypes[0]
}

func (x RuleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleStatus.Descriptor instead.
func (RuleStatus) EnumDescriptor() ([]byte, []int) {
	return file_meadplugin_proto_rawDescGZIP(), []int{0}
}

type IdentifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifyRequest) Reset() {
	*x = IdentifyRequest{}
	mi := &file_meadplugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyRequest) ProtoMessage() {}

func (x *IdentifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meadplugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyRequest.ProtoReflect.Descriptor instead.
func (*IdentifyRequest) Descriptor() ([]byte, []int) {
	return file_meadplugin_proto_rawDescGZIP(), []int{0}
}

type IdentifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Rules         []string               `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifyResponse) Reset() {
	*x = IdentifyResponse{}
	mi := &file_meadplugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyResponse) ProtoMessage() {}

func (x *IdentifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meadplugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyResponse.ProtoReflect.Descriptor instead.
func (*IdentifyResponse) Descriptor() ([]byte, []int) {
	return file_meadplugin_proto_rawDescGZIP(), []int{1}
}

func (x *IdentifyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IdentifyResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *IdentifyResponse) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type HelpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Rule          string                 `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelpRequest) Reset() {
	*x = HelpRequest{}
	mi := &file_meadplugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelpRequest) ProtoMessage() {}

func (x *HelpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meadplugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelpRequest.ProtoReflect.Descriptor instead.
func (*HelpRequest) Descriptor() ([]byte, []int) {
	return file_meadplugin_proto_rawDescGZIP(), []int{2}
}

func (x *HelpRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HelpRequest) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

type HelpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Short         string                 `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
	Long          string                 `protobuf:"bytes,2,opt,name=long,proto3" json:"long,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelpResponse) Reset() {
	*x = HelpResponse{}
	mi := &file_meadplugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelpResponse) ProtoMessage() {}

func (x *HelpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meadplugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelpResponse.ProtoReflect.Descriptor instead.
func (*HelpResponse) Descriptor() ([]byte, []int) {
	return file_meadplugin_proto_rawDescGZIP(), []int{3}
}

func (x *HelpResponse) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *HelpResponse) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

type EvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Rule          string                 `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_meadplugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meadplugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_meadplugin_proto_rawDescGZIP(), []int{4}
}

func (x *EvaluateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EvaluateRequest) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *EvaluateRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_meadplugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_meadplugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_meadplugin_proto_rawDescGZIP(), []int{5}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EvaluateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        RuleStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=meadplugin.RuleStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Items         []*Item                `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_meadplugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meadplugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_meadplugin_proto_rawDescGZIP(), []int{6}
}

func (x *EvaluateResponse) GetStatus() RuleStatus {
	if x != nil {
		return x.Status
	}
	return RuleStatus_RULE_STATUS_UNSPECIFIED
}

func (x *EvaluateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EvaluateResponse) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *EvaluateResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_meadplugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meadplugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_meadplugin_proto_rawDescGZIP(), []int{7}
}

func (x *InsertRequest) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_meadplugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meadplugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_meadplugin_proto_rawDescGZIP(), []int{8}
}

func (x *InsertResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InsertResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_meadplugin_proto protoreflect.FileDescriptor

const file_meadplugin_proto_rawDesc = "" +
	"\n" +
	"\x10meadplugin.proto\x12\n" +
	"meadplugin\"\x11\n" +
	"\x0fIdentifyRequest\"V\n" +
	"\x10IdentifyResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05rules\x18\x03 \x03(\tR\x05rules\"@\n" +
	"\vHelpRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04rule\x18\x02 \x01(\tR\x04rule\"8\n" +
	"\fHelpResponse\x12\x14\n" +
	"\x05short\x18\x01 \x01(\tR\x05short\x12\x12\n" +
	"\x04long\x18\x02 \x01(\tR\x04long\"\xc0\x01\n" +
	"\x0fEvaluateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04rule\x18\x02 \x01(\tR\x04rule\x12?\n" +
	"\x06params\x18\x03 \x03(\v2'.meadplugin.EvaluateRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\bmetadata\x18\x02 \x03(\v2\x1e.meadplugin.Item.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x02\n" +
	"\x10EvaluateResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.meadplugin.RuleStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12@\n" +
	"\x06params\x18\x03 \x03(\v2(.meadplugin.EvaluateResponse.ParamsEntryR\x06params\x12&\n" +
	"\x05items\x18\x04 \x03(\v2\x10.meadplugin.ItemR\x05items\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\rInsertRequest\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.meadplugin.ItemR\x05items\"B\n" +
	"\x0eInsertResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x88\x01\n" +
	"\n" +
	"RuleStatus\x12\x1b\n" +
	"\x17RULE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RULE_STATUS_SUCCESS\x10\x01\x12\x17\n" +
	"\x13RULE_STATUS_FAILURE\x10\x02\x12\x15\n" +
	"\x11RULE_STATUS_RETRY\x10\x03\x12\x14\n" +
	"\x10RULE_STATUS_SKIP\x10\x042\x9e\x02\n" +
	"\n" +
	"meadplugin\x12G\n" +
	"\bIdentify\x12\x1b.meadplugin.IdentifyRequest\x1a\x1c.meadplugin.IdentifyResponse\"\x00\x12;\n" +
	"\x04Help\x12\x17.meadplugin.HelpRequest\x1a\x18.meadplugin.HelpResponse\"\x00\x12G\n" +
	"\bEvaluate\x12\x1b.meadplugin.EvaluateRequest\x1a\x1c.meadplugin.EvaluateResponse\"\x00\x12A\n" +
	"\x06Insert\x12\x19.meadplugin.InsertRequest\x1a\x1a.meadplugin.InsertResponse\"\x00B\x0eZ\f.;meadpluginb\x06proto3"

var (
	file_meadplugin_proto_rawDescOnce sync.Once
	file_meadplugin_proto_rawDescData []byte
)

func file_meadplugin_proto_rawDescGZIP() []byte {
	file_meadplugin_proto_rawDescOnce.Do(func() {
		file_meadplugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meadplugin_proto_rawDesc), len(file_meadplugin_proto_rawDesc)))
	})
	return file_meadplugin_proto_rawDescData
}

var file_meadplugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meadplugin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_meadplugin_proto_goTypes = []any{
	(RuleStatus)(0),          // 0: meadplugin.RuleStatus
	(*IdentifyRequest)(nil),  // 1: meadplugin.IdentifyRequest
	(*IdentifyResponse)(nil), // 2: meadplugin.IdentifyResponse
	(*HelpRequest)(nil),      // 3: meadplugin.HelpRequest
	(*HelpResponse)(nil),     // 4: meadplugin.HelpResponse
	(*EvaluateRequest)(nil),  // 5: meadplugin.EvaluateRequest
	(*Item)(nil),             // 6: meadplugin.Item
	(*EvaluateResponse)(nil), // 7: meadplugin.EvaluateResponse
	(*InsertRequest)(nil),    // 8: meadplugin.InsertRequest
	(*InsertResponse)(nil),   // 9: meadplugin.InsertResponse
	nil,                      // 10: meadplugin.EvaluateRequest.ParamsEntry
	nil,                      // 11: meadplugin.Item.MetadataEntry
	nil,                      // 12: meadplugin.EvaluateResponse.ParamsEntry
}
var file_meadplugin_proto_depIdxs = []int32{
	10, // 0: meadplugin.EvaluateRequest.params:type_name -> meadplugin.EvaluateRequest.ParamsEntry
	11, // 1: meadplugin.Item.metadata:type_name -> meadplugin.Item.MetadataEntry
	0,  // 2: meadplugin.EvaluateResponse.status:type_name -> meadplugin.RuleStatus
	12, // 3: meadplugin.EvaluateResponse.params:type_name -> meadplugin.EvaluateResponse.ParamsEntry
	6,  // 4: meadplugin.EvaluateResponse.items:type_name -> meadplugin.Item
	6,  // 5: meadplugin.InsertRequest.items:type_name -> meadplugin.Item
	1,  // 6: meadplugin.meadplugin.Identify:input_type -> meadplugin.IdentifyRequest
	3,  // 7: meadplugin.meadplugin.Help:input_type -> meadplugin.HelpRequest
	5,  // 8: meadplugin.meadplugin.Evaluate:input_type -> meadplugin.EvaluateRequest
	8,  // 9: meadplugin.meadplugin.Insert:input_type -> meadplugin.InsertRequest
	2,  // 10: meadplugin.meadplugin.Identify:output_type -> meadplugin.IdentifyResponse
	4,  // 11: meadplugin.meadplugin.Help:output_type -> meadplugin.HelpResponse
	7,  // 12: meadplugin.meadplugin.Evaluate:output_type -> meadplugin.EvaluateResponse
	9,  // 13: meadplugin.meadplugin.Insert:output_type -> meadplugin.InsertResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_meadplugin_proto_init() }
func file_meadplugin_proto_init() {
	if File_meadplugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meadplugin_proto_rawDesc), len(file_meadplugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meadplugin_proto_goTypes,
		DependencyIndexes: file_meadplugin_proto_depIdxs,
		EnumInfos:         file_meadplugin_proto_enumTypes,
		MessageInfos:      file_meadplugin_proto_msgTypes,
	}.Build()
	File_meadplugin_proto = out.File
	file_meadplugin_proto_goTypes = nil
	file_meadplugin_proto_depIdxs = nil
}
