# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meadplugin.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10meadplugin.proto\x12\nmeadplugin\"\x11\n\x0fIdentifyRequest\"@\n\x10IdentifyResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\r\n\x05rules\x18\x03 \x03(\t\"\x87\x01\n\x0f\x45valuateRequest\x12\x0c\n\x04rule\x18\x01 \x01(\t\x12\x37\n\x06params\x18\x02 \x03(\x0b\x32\'.meadplugin.EvaluateRequest.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xc3\x01\n\x10\x45valuateResponse\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.meadplugin.RuleStatus\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x38\n\x06params\x18\x03 \x03(\x0b\x32(.meadplugin.EvaluateResponse.ParamsEntry\x12\r\n\x05\x66iles\x18\x04 \x03(\t\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1e\n\rInsertRequest\x12\r\n\x05\x66iles\x18\x01 \x03(\t\" \n\x0eInsertResponse\x12\x0e\n\x06status\x18\x01 \x01(\t*\x88\x01\n\nRuleStatus\x12\x1b\n\x17RULE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n\x13RULE_STATUS_SUCCESS\x10\x01\x12\x17\n\x13RULE_STATUS_FAILURE\x10\x02\x12\x15\n\x11RULE_STATUS_RETRY\x10\x03\x12\x14\n\x10RULE_STATUS_SKIP\x10\x04\x32\xe1\x01\n\nmeadplugin\x12G\n\x08Identify\x12\x1b.meadplugin.IdentifyRequest\x1a\x1c.meadplugin.IdentifyResponse\"\x00\x12G\n\x08\x45valuate\x12\x1b.meadplugin.EvaluateRequest\x1a\x1c.meadplugin.EvaluateResponse\"\x00\x12\x41\n\x06Insert\x12\x19.meadplugin.InsertRequest\x1a\x1a.meadplugin.InsertResponse\"\x00\x42\x0eZ\x0c.;meadpluginb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meadplugin_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\014.;meadplugin'
  _EVALUATEREQUEST_PARAMSENTRY._options = None
  _EVALUATEREQUEST_PARAMSENTRY._serialized_options = b'8\001'
  _EVALUATERESPONSE_PARAMSENTRY._options = None
  _EVALUATERESPONSE_PARAMSENTRY._serialized_options = b'8\001'
  _RULESTATUS._serialized_start=520
  _RULESTATUS._serialized_end=656
  _IDENTIFYREQUEST._serialized_start=32
  _IDENTIFYREQUEST._serialized_end=49
  _IDENTIFYRESPONSE._serialized_start=51
  _IDENTIFYRESPONSE._serialized_end=115
  _EVALUATEREQUEST._serialized_start=118
  _EVALUATEREQUEST._serialized_end=253
  _EVALUATEREQUEST_PARAMSENTRY._serialized_start=208
  _EVALUATEREQUEST_PARAMSENTRY._serialized_end=253
  _EVALUATERESPONSE._serialized_start=256
  _EVALUATERESPONSE._serialized_end=451
  _EVALUATERESPONSE_PARAMSENTRY._serialized_start=208
  _EVALUATERESPONSE_PARAMSENTRY._serialized_end=253
  _INSERTREQUEST._serialized_start=453
  _INSERTREQUEST._serialized_end=483
  _INSERTRESPONSE._serialized_start=485
  _INSERTRESPONSE._serialized_end=517
  _MEADPLUGIN._serialized_start=659
  _MEADPLUGIN._serialized_end=884
# @@protoc_insertion_point(module_scope)
