# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import meadplugin_pb2 as meadplugin__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in meadplugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class meadpluginStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Identify = channel.unary_unary(
                '/meadplugin.meadplugin/Identify',
                request_serializer=meadplugin__pb2.IdentifyRequest.SerializeToString,
                response_deserializer=meadplugin__pb2.IdentifyResponse.FromString,
                _registered_method=True)
        self.Help = channel.unary_unary(
                '/meadplugin.meadplugin/Help',
                request_serializer=meadplugin__pb2.HelpRequest.SerializeToString,
                response_deserializer=meadplugin__pb2.HelpResponse.FromString,
                _registered_method=True)
        self.Evaluate = channel.unary_unary(
                '/meadplugin.meadplugin/Evaluate',
                request_serializer=meadplugin__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=meadplugin__pb2.EvaluateResponse.FromString,
                _registered_method=True)
        self.Insert = channel.unary_unary(
                '/meadplugin.meadplugin/Insert',
                request_serializer=meadplugin__pb2.InsertRequest.SerializeToString,
                response_deserializer=meadplugin__pb2.InsertResponse.FromString,
                _registered_method=True)


class meadpluginServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Identify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Help(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evaluate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_meadpluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Identify': grpc.unary_unary_rpc_method_handler(
                    servicer.Identify,
                    request_deserializer=meadplugin__pb2.IdentifyRequest.FromString,
                    response_serializer=meadplugin__pb2.IdentifyResponse.SerializeToString,
            ),
            'Help': grpc.unary_unary_rpc_method_handler(
                    servicer.Help,
                    request_deserializer=meadplugin__pb2.HelpRequest.FromString,
                    response_serializer=meadplugin__pb2.HelpResponse.SerializeToString,
            ),
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=meadplugin__pb2.EvaluateRequest.FromString,
                    response_serializer=meadplugin__pb2.EvaluateResponse.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=meadplugin__pb2.InsertRequest.FromString,
                    response_serializer=meadplugin__pb2.InsertResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meadplugin.meadplugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meadplugin.meadplugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class meadplugin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Identify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meadplugin.meadplugin/Identify',
            meadplugin__pb2.IdentifyRequest.SerializeToString,
            meadplugin__pb2.IdentifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Help(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meadplugin.meadplugin/Help',
            meadplugin__pb2.HelpRequest.SerializeToString,
            meadplugin__pb2.HelpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meadplugin.meadplugin/Evaluate',
            meadplugin__pb2.EvaluateRequest.SerializeToString,
            meadplugin__pb2.EvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meadplugin.meadplugin/Insert',
            meadplugin__pb2.InsertRequest.SerializeToString,
            meadplugin__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
